name: geo-ml
channels:
  - conda-forge
dependencies:
  - boto3                                             # S3 storage client
  - folium          # Interactive maps
  - gdal                  # Spatial data input/output
  - geopandas                               # Vector data
  - git
  - pip
  - stackstac                               # Get data from STAC
  - pystac-client                         # Search data from STAC
  - python=3.12
  - rasterio                                  # raster data handling
  - libgdal-jp2openjpeg
  - rioxarray                               # Save to geotiff from xarray
  - jupyterlab
  - jupyterlab-git
  - jupyter-resource-usage
  - ipywidgets
  - mapclassify           # Interactive maps
  - matplotlib
  - seaborn
  - pip:
    - addict                # SAM
    - groundingdino-py      # SAM
    - huggingface_hub       # Huggingface
    - imbalanced-learn              # Imbalanced data handling
    - pycocotools           # SAM
    - sahi                                                # Tiled object detection
    - scikit-learn                          # Shallow machine learning
    - segment-geospatial[samgeo2] # Segment-anything
    - supervision           # SAM
    - tokenizers            # SAM
    - torchgeo                                  # CNN geo library
    - torchinfo                                 # Plot pytorch model info
    - torchvision
    - transformers
    - ultralytics                             # Object detection with YOLO
    - yapf
    - git+https://github.com/mayrajeo/geo2ml.git # Prepare data for YOLO
