channels:
  - conda-forge
dependencies:
  - jupyterlab #>= 3.4.7
  - matplotlib #>= 3.6.0 
  - seaborn #>= 0.12.0 
  - rasterio #>= 1.3.2 
  - geopandas #>= 0.11.1 
  - scikit-learn #>= 1.1.2 
  - tensorflow #>= 2.10.0 
  - imbalanced-learn #>= 0.9.1 
  - jupyterlab-git #>= 0.39.3
  - pystac #>= 1.6.1
  - pystac-client #>= 0.5.0
  - stackstac #>= 0.4.1
  - rioxarray #>= 0.12.0
