channels:
  - conda-forge
dependencies:
  - jupyterlab #>= 3.4.7
  - matplotlib #>= 3.6.0 #basic plotting
  - seaborn #>= 0.12.0 # more fancy plotting
  - rasterio #>= 1.3.2 # raster data handling
  - geopandas #>= 0.11.1 #vector data handling
  - scikit-learn #>= 1.1.2 #basic machine learning and data science
  - tensorflow #>= 2.10.0 #advanced deep learning
  - imbalanced-learn #>= 0.9.1 #for imbalanced classes
  - jupyterlab-git #>= 0.39.3
  - pystac #>= 1.6.1
  - pystac-client #>= 0.5.0
  - stackstac #>= 0.4.1
  - rioxarray #>= 0.12.0
