channels:
  - conda-forge
dependencies:
  - addict
  - boto3 					      # S3 storage client
  - folium
  - gdal
  - geopandas 				    # Vector data
  - groundingdino-py
  - huggingface_hub
  - imbalanced-learn 		  # Imbalanced data handling
  - jupyterlab 
  - mapclassify
  - matplotlib				    
  - pip
  - pystac-client 			  # Search data from STAC 
  - rasterio 				      # raster data handling
  - rioxarray 				    # Save to geotiff from xarray
  - sahi 					        # Tiled object detection
  - scikit-learn   			  # Shallow machine learning 
  - segment-geospatial[samgeo2] # Segment-anything
  - stackstac 				    # Get data from STAC
  - supervision
  - tokenizers
  - torchgeo				      # CNN geo library
  - torchinfo				      # Plot pytorch model info
  - torchvision==0.22
  - transformers			
  - ultralytics				    # Object detection with YOLO
  - yapf
  - pip:
    - git+https://github.com/mayrajeo/geo2ml.git # Prepare data for YOLO
